version: "3.9"
services:
  www:
    container_name: "www"
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./src:/var/www/html/src
      - ./tests:/var/www/html/tests
      - ./script.php:/var/www/html/script.php