version: "3.9"
services:
  www:
    container_name: "www"
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./config:/var/www/html/config
      - ./src:/var/www/html/src
      - ./tests:/var/www/html/tests
      - ./script.php:/var/www/html/script.php
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
