services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.

  DY\CFC\:
    resource: '../src/*'

  DY\CFC\CommissionFeeCalculatorApplication:
    public: true
